In [738]:
import requests
import os
import json
import numpy as np
import pandas as pd

from pprint import pprint
import pytz
import seaborn as sb


from datetime import datetime
from datetime import timedelta
from datetime import date

import time
from PIL import Image
from IPython.display import display
from concurrent.futures import ThreadPoolExecutor, as_completed

# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import json

pd.options.mode.chained_assignment = None
import re
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import warnings
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, RFE, mutual_info_classif
import requests

import asyncio
import aiohttp
import nest_asyncio
import math

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

### Roster Pull

In [739]:
# # Roster Data
# team_url = "https://api.nhle.com/stats/rest/en/team"

# response = requests.get(team_url)
# content = json.loads(response.content)

# # Send an HTTP GET request to the specified URL
# response = requests.get(team_url)

# # Check if the request was successful (status code 200)
# if response.status_code == 200:
#     # The response content can be accessed using response.text
#     response_text = response.text
#     # pprint(response_text)
# else:
#     print(f"Request failed with status code {response.status_code}")

# json_data = json.loads(response_text)
# json_data.keys()

In [740]:

# roster = json_data["data"]
# # # for 26-27 season :
# valid_team_codes = set(range(1, 11)).union(set(range(12, 27))).union(set(range(28, 31))).union(set(range(52, 53))).union(set(range(54, 56))).union(set(range(59, 60))).union(set(range(68, 69)))

In [741]:
# df_roster = pd.DataFrame(roster)
# df_roster = df_roster.convert_dtypes()
# df_roster["roster_url"] = (
#     "https://api-web.nhle.com/v1/roster/" + df_roster["triCode"] + "/20242025"
# )
# df_roster = df_roster[["id", "fullName", "triCode", "roster_url"]]
# df_roster = df_roster.rename(
#     columns={"id": "team_id", "fullName": "team_name", "triCode": "tri_code"}
# )
# df = df_roster.sort_values(by="team_id")
# filtered_rosters = df_roster[df_roster['team_id'].isin(valid_team_codes)]
# filtered_rosters
# # Create an empty dictionary to store the results
# roster_dict = {}
# roster_link = filtered_rosters["roster_url"]


# # Define your extraction script as a function
# def extract_roster_data(roster_link):
#     try:
#         # Send an HTTP GET request to the game URL
#         response = requests.get(roster_link)

#         # Check if the request was successful (status code 200)
#         if response.status_code == 200:
#             response_text = response.text
#             json_data = json.loads(response_text)

#             forwards = json_data["forwards"]
#             forwards_df = pd.DataFrame(forwards)
#             forwards_df = forwards_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             forwards_df["firstName"] = forwards_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             forwards_df["lastName"] = forwards_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             forwards_df["player_name"] = (
#                 forwards_df["firstName"] + " " + forwards_df["lastName"]
#             )
#             forwards_roster = forwards_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]

#             defense = json_data["defensemen"]
#             defense_df = pd.DataFrame(defense)
#             defense_df = defense_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             defense_df["firstName"] = defense_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             defense_df["lastName"] = defense_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             defense_df["player_name"] = (
#                 defense_df["firstName"] + " " + defense_df["lastName"]
#             )
#             defense_roster = defense_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]

#             goalies = json_data["goalies"]
#             goalies_df = pd.DataFrame(goalies)
#             goalies_df = goalies_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             goalies_df["firstName"] = goalies_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             goalies_df["lastName"] = goalies_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             goalies_df["player_name"] = (
#                 goalies_df["firstName"] + " " + goalies_df["lastName"]
#             )
#             goalie_roster = goalies_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             # Append all data to form a single team roster
#             team_roster_df = pd.concat(
#                 [forwards_roster, defense_roster, goalie_roster],
#                 axis=0,
#                 ignore_index=True,
#             )

#             team_roster_df["id"] = team_roster_df["id"].astype(float, errors="ignore")

#             def extract_tricode(link):
#                 # Use a regular expression to find the tricode
#                 match = re.search(r"/([A-Z]{3})/", link)
#                 if match:
#                     return match.group(1)
#                 else:
#                     # Return None if no match is found
#                     return None

#             team_roster_df["tri_code"] = team_roster_df["headshot"].apply(
#                 extract_tricode
#             )
#             return team_roster_df  # Return the entire processed DataFrame
#         else:
#             print(
#                 f"Request failed for {roster_link} with status code {response.status_code}"
#             )
#             return None  # Return None to indicate failure

#     except Exception as e:
#         print(f"An error occurred: {e}")
#         return None  # Return None to indicate failure


# # Loop through the rows of the filtered_rosters df
# for index, row in filtered_rosters.iterrows():
#     # Extract the API link from the current row
#     roster_link = row["roster_url"]

#     # Run your game-specific data script and get the entire processed DataFrame
#     team_roster = extract_roster_data(roster_link)

#     # Check if team_roster is not None before proceeding
#     if team_roster is not None:
#         # Add a 'game_id' column to the game_specific_data DataFrame
#         team_roster["tri_code"] = row["tri_code"]

#         # Store the result in the dictionary with the game ID as the key
#         roster_dict[row["tri_code"]] = team_roster
#     else:
#         print(f"Skipping row {index} due to failed request or exception.")

# all_rosters = pd.concat(roster_dict.values(), ignore_index=True)

# team_rosters_24 = filtered_rosters[["team_id", "team_name", "tri_code"]]
# team_rosters_24 = team_rosters_24.merge(all_rosters, on="tri_code", how="left")
# team_rosters_24 = team_rosters_24.rename(columns={"id": "player_id"})

# export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\team_rosters_24.csv"
# team_rosters_24.to_csv(export_path, index=False)

In [742]:
# df_roster = pd.DataFrame(roster)
# df_roster = df_roster.convert_dtypes()
# df_roster["roster_url"] = (
#     "https://api-web.nhle.com/v1/roster/" + df_roster["triCode"] + "/20252026"
# )
# df_roster = df_roster[["id", "fullName", "triCode", "roster_url"]]
# df_roster = df_roster.rename(
#     columns={"id": "team_id", "fullName": "team_name", "triCode": "tri_code"}
# )
# df = df_roster.sort_values(by="team_id")
# filtered_rosters = df_roster[df_roster['team_id'].isin(valid_team_codes)]

# # Create an empty dictionary to store the results
# roster_dict = {}
# roster_link = filtered_rosters["roster_url"]


# # Define your extraction script as a function
# def extract_roster_data(roster_link):
#     try:
#         # Send an HTTP GET request to the game URL
#         response = requests.get(roster_link)

#         # Check if the request was successful (status code 200)
#         if response.status_code == 200:
#             response_text = response.text
#             json_data = json.loads(response_text)

#             forwards = json_data["forwards"]
#             forwards_df = pd.DataFrame(forwards)
#             forwards_df = forwards_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             forwards_df["firstName"] = forwards_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             forwards_df["lastName"] = forwards_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             forwards_df["player_name"] = (
#                 forwards_df["firstName"] + " " + forwards_df["lastName"]
#             )
#             forwards_roster = forwards_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]

#             defense = json_data["defensemen"]
#             defense_df = pd.DataFrame(defense)
#             defense_df = defense_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             defense_df["firstName"] = defense_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             defense_df["lastName"] = defense_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             defense_df["player_name"] = (
#                 defense_df["firstName"] + " " + defense_df["lastName"]
#             )
#             defense_roster = defense_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]

#             goalies = json_data["goalies"]
#             goalies_df = pd.DataFrame(goalies)
#             goalies_df = goalies_df[
#                 [
#                     "id",
#                     "headshot",
#                     "firstName",
#                     "lastName",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             goalies_df["firstName"] = goalies_df["firstName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             goalies_df["lastName"] = goalies_df["lastName"].apply(
#                 lambda x: x["default"] if isinstance(x, dict) else x
#             )
#             goalies_df["player_name"] = (
#                 goalies_df["firstName"] + " " + goalies_df["lastName"]
#             )
#             goalie_roster = goalies_df[
#                 [
#                     "id",
#                     "headshot",
#                     "player_name",
#                     "sweaterNumber",
#                     "positionCode",
#                     "shootsCatches",
#                 ]
#             ]
#             # Append all data to form a single team roster
#             team_roster_df = pd.concat(
#                 [forwards_roster, defense_roster, goalie_roster],
#                 axis=0,
#                 ignore_index=True,
#             )

#             team_roster_df["id"] = team_roster_df["id"].astype(float, errors="ignore")

#             def extract_tricode(link):
#                 # Use a regular expression to find the tricode
#                 match = re.search(r"/([A-Z]{3})/", link)
#                 if match:
#                     return match.group(1)
#                 else:
#                     # Return None if no match is found
#                     return None

#             team_roster_df["tri_code"] = team_roster_df["headshot"].apply(
#                 extract_tricode
#             )
#             return team_roster_df  # Return the entire processed DataFrame
#         else:
#             print(
#                 f"Request failed for {roster_link} with status code {response.status_code}"
#             )
#             return None  # Return None to indicate failure

#     except Exception as e:
#         print(f"An error occurred: {e}")
#         return None  # Return None to indicate failure


# # Loop through the rows of the filtered_rosters df
# for index, row in filtered_rosters.iterrows():
#     # Extract the API link from the current row
#     roster_link = row["roster_url"]

#     # Run your game-specific data script and get the entire processed DataFrame
#     team_roster = extract_roster_data(roster_link)

#     # Check if team_roster is not None before proceeding
#     if team_roster is not None:
#         # Add a 'game_id' column to the game_specific_data DataFrame
#         team_roster["tri_code"] = row["tri_code"]

#         # Store the result in the dictionary with the game ID as the key
#         roster_dict[row["tri_code"]] = team_roster
#     else:
#         print(f"Skipping row {index} due to failed request or exception.")

# all_rosters = pd.concat(roster_dict.values(), ignore_index=True)

# team_rosters_25 = filtered_rosters[["team_id", "team_name", "tri_code"]]
# team_rosters_25 = team_rosters_25.merge(all_rosters, on="tri_code", how="left")
# team_rosters_25 = team_rosters_25.rename(columns={"id": "player_id"})

# export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\team_rosters_25.csv"
# team_rosters_25.to_csv(export_path, index=False)

### Rosters

In [743]:
team_rosters_25 = pd.read_csv(r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\team_rosters_25.csv")
team_rosters_24 = pd.read_csv(r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\team_rosters_24.csv")

In [744]:

teams = team_rosters_25[['team_id','team_name','tri_code']].drop_duplicates().sort_values(by='team_id').reset_index(drop=True)
teams = teams.rename(columns = {'team_id':'team_id_2526', 'team_name':'team_name_2526','tri_code':'tri_code_2526' })

rows_to_drop = [59]
teams = teams[~teams["team_id_2526"].isin(rows_to_drop)].copy()

In [745]:

players_2425 = team_rosters_24[['player_id', 'player_name', 'team_id', 'tri_code', 'team_name']]
players_2425=players_2425.rename(columns = {'team_id':'team_id_2425', 'team_name':'team_name_2425', 'tri_code':'tri_code_2425'})

players_2425['team_id_2425'] = np.where(players_2425['team_id_2425'] == 59, 68, players_2425['team_id_2425'])
players_2425['team_name_2425'] = np.where(players_2425['team_name_2425'] == 'Utah Hockey Club', 'Utah Mammoth', players_2425['team_name_2425'])
players_2425 = players_2425.drop_duplicates()

players_2425.head()

   player_id    player_name  team_id_2425 tri_code_2425      team_name_2425
0    8476981  Josh Anderson             8           MTL  Montréal Canadiens
1    8476469     Joel Armia             8           MTL  Montréal Canadiens
2    8481540  Cole Caufield             8           MTL  Montréal Canadiens
3    8481523     Kirby Dach             8           MTL  Montréal Canadiens
4    8484984   Ivan Demidov             8           MTL  Montréal Canadiens

In [746]:

players_2526 = team_rosters_25[['player_id', 'player_name', 'team_id', 'tri_code', 'team_name']]
players_2526=players_2526.rename(columns = {'team_id':'team_id_2526', 'team_name':'team_name_2526', 'tri_code':'tri_code_2526'})
players_2526['team_id_2526'] = np.where(players_2526['team_id_2526'] == 59, 68, players_2526['team_id_2526'])
players_2526['team_name_2526'] = np.where(players_2526['team_name_2526'] == 'Utah Hockey Club', 'Utah Mammoth', players_2526['team_name_2526'])
players_2526=players_2526.drop_duplicates()

players_2526.head()

   player_id     player_name  team_id_2526 tri_code_2526      team_name_2526
0  8476981.0   Josh Anderson             8           MTL  Montréal Canadiens
1  8483424.0       Owen Beck             8           MTL  Montréal Canadiens
2  8482737.0  Zachary Bolduc             8           MTL  Montréal Canadiens
3  8481540.0   Cole Caufield             8           MTL  Montréal Canadiens
4  8481523.0      Kirby Dach             8           MTL  Montréal Canadiens

In [747]:

players=players_2425.merge(players_2526, on=['player_id', 'player_name'], how = 'left').drop_duplicates()
col_order = ['player_id', 'player_name', 'team_id_2425', 'tri_code_2425', 'team_name_2425', 'team_id_2526', 'tri_code_2526', 'team_name_2526']
ordered_cols = [c for c in col_order if c in players.columns]

# Reorder dataframe
players = players[ordered_cols]
players.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
0,8476981,Josh Anderson,8,MTL,Montréal Canadiens,8.0,MTL,Montréal Canadiens
1,8476469,Joel Armia,8,MTL,Montréal Canadiens,26.0,LAK,Los Angeles Kings
2,8481540,Cole Caufield,8,MTL,Montréal Canadiens,8.0,MTL,Montréal Canadiens
3,8481523,Kirby Dach,8,MTL,Montréal Canadiens,8.0,MTL,Montréal Canadiens
4,8484984,Ivan Demidov,8,MTL,Montréal Canadiens,8.0,MTL,Montréal Canadiens

In [748]:
players = players.dropna(subset=["player_id","team_id_2425", 'team_name_2425'])

In [749]:

players = players.drop_duplicates()

players['team_id_2526'] = players['team_id_2526'].astype('Int64')
players['player_id'] = players['player_id'].astype('Int64')

In [750]:
players[players['player_name'].str.contains('marner', case=False, na=False)]

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
757,8478483,Mitch Marner,10,TOR,Toronto Maple Leafs,54,VGK,Vegas Golden Knights

### Split Team Data

In [751]:

split_goalies= pd.read_csv(r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\split_goalies.csv")
split_goalies=split_goalies[['Player', 'Team','GP']].sort_values(by=['Player', 'GP'], ascending=[True, False])

split_players = pd.read_csv(r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\split_times_2026.csv")
split_players= split_players[['Player', 'Team', 'GP']].sort_values(by=['Player', 'GP'], ascending=[True, False])

all_split_players = pd.concat([split_players, split_goalies])
all_split_players.head()

           Player Team  GP
327    A.J. Greer  FLA  78
423  Aaron Ekblad  FLA  72
669     Aatu Raty  VAN  66
859   Abram Wiebe  CGY   4
754  Adam Boqvist  NYI  28

In [752]:
#first, ID players who had been traded during the season
traded_ufas=all_split_players[['Player', 'Team', 'GP']].sort_values(by=['Player', 'GP'], ascending=[True, False])
traded_ufas = traded_ufas[traded_ufas["Player"].duplicated(keep=False)]
traded_ufas.head(10)

                Player Team  GP
228   Alexandre Texier  MTL  43
565   Alexandre Texier  STL   8
464  Andrew Mangiapane  EDM  52
709  Andrew Mangiapane  CHI  10
31      Artemi Panarin  NYR  52
72      Artemi Panarin  L.A  26
177        Bobby Brink  PHI  55
390        Bobby Brink  MIN  13
536       Bobby McMann  TOR  60
531       Bobby McMann  SEA  18

In [753]:
#Id the team that they ended with

ending_teams = traded_ufas.drop_duplicates(
    subset=["Player"],
    keep="last"
)

ending_teams = ending_teams.sort_values(by='Player').reset_index(drop=True)

ending_teams = ending_teams.rename(columns = {'Player':'player_name', 'Team':'tri_code_2526'}).drop(columns= 'GP')

### Off season trades

In [754]:
off_season_trade = all_split_players[['Player', 'Team']].drop_duplicates(keep=False).reset_index(drop=True)
off_season_trade['Team'] = np.where(off_season_trade['Team']=='T.B', 'TBL', off_season_trade['Team'])
off_season_trade['Team'] = np.where(off_season_trade['Team']=='N.J', 'NJD', off_season_trade['Team'])
off_season_trade['Team'] = np.where(off_season_trade['Team']=='L.A', 'LAK', off_season_trade['Team'])
off_season_trade['Team'] = np.where(off_season_trade['Team']=='S.J', 'SJS', off_season_trade['Team'])

In [755]:
players[players['player_name'].str.contains('markstr', case=False, na=False)]

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
211,8474593,Jacob Markstrom,1,NJD,New Jersey Devils,13,FLA,Florida Panthers

In [756]:
off_season_trade=off_season_trade.rename(columns = {'Player':'player_name'})
off_season_trade.head()

    player_name Team
0    A.J. Greer  FLA
1  Aaron Ekblad  FLA
2     Aatu Raty  VAN
3   Abram Wiebe  CGY
4  Adam Boqvist  NYI

In [757]:
#These players have active contracts and currently sit on a roster
non_fa_players = players[players['team_id_2526'].notna()]
non_fa_players.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
0,8476981,Josh Anderson,8,MTL,Montréal Canadiens,8,MTL,Montréal Canadiens
1,8476469,Joel Armia,8,MTL,Montréal Canadiens,26,LAK,Los Angeles Kings
2,8481540,Cole Caufield,8,MTL,Montréal Canadiens,8,MTL,Montréal Canadiens
3,8481523,Kirby Dach,8,MTL,Montréal Canadiens,8,MTL,Montréal Canadiens
4,8484984,Ivan Demidov,8,MTL,Montréal Canadiens,8,MTL,Montréal Canadiens

In [758]:
off_season_trade =off_season_trade.merge(non_fa_players, on='player_name', how = 'inner')
x_cols = [c for c in off_season_trade.columns if c.endswith("_x")]

for x in x_cols:
    base = x[:-2]              # remove "_x"
    y = f"{base}_y"

    if y in off_season_trade.columns:
        off_season_trade[base] = off_season_trade[x].combine_first(off_season_trade[y])
        off_season_trade.drop(columns=[x, y], inplace=True)
off_season_trade.head()

,player_name,Team,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
0,A.J. Greer,FLA,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks
1,Aaron Ekblad,FLA,8477932,13,FLA,Florida Panthers,13,FLA,Florida Panthers
2,Adam Edstrom,NYR,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators
3,Adam Fantilli,CBJ,8484166,29,CBJ,Columbus Blue Jackets,29,CBJ,Columbus Blue Jackets
4,Adam Fox,NYR,8479323,3,NYR,New York Rangers,3,NYR,New York Rangers

In [759]:
#ID only the players who had been traded in the off season 
off_season_trade['action'] = np.where(off_season_trade['Team']!=off_season_trade['tri_code_2526'], "off-season trade", "")
off_season_trade = off_season_trade[off_season_trade['action']=='off-season trade'].drop_duplicates()
off_season_trade.head()

,player_name,Team,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action
0,A.J. Greer,FLA,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade
2,Adam Edstrom,NYR,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade
18,Alex Tuch,BUF,8477949,7,BUF,Buffalo Sabres,15,WSH,Washington Capitals,off-season trade
27,Alexandre Texier,STL,8480074,19,STL,St. Louis Blues,8,MTL,Montréal Canadiens,off-season trade
31,Andre Burakovsky,CHI,8477444,16,CHI,Chicago Blackhawks,9,OTT,Ottawa Senators,off-season trade

In [761]:
off_season_trade = off_season_trade.drop(columns = 'Team')

### Free Agents

In [762]:
# players who do not currently sit on a roster
free_agents = players[players['team_id_2526'].isna()]
free_agents.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526
8,8479339,Patrik Laine,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
10,8479543,Michael Pezzetta,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
18,8475233,David Savard,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
27,8478043,Sam Lafferty,7,BUF,Buffalo Sabres,<NA>,NaN,NaN
36,8480196,Jacob Bryson,7,BUF,Buffalo Sabres,<NA>,NaN,NaN

In [763]:
#Updating the 25-26 teams for players who were traded in-season and still went to free agency

free_agents = free_agents.merge(ending_teams, on='player_name', how='left')
x_cols = [c for c in free_agents.columns if c.endswith("_x")]

for x in x_cols:
    base = x[:-2]              # remove "_x"
    y = f"{base}_y"

    if y in free_agents.columns:
        free_agents[base] = free_agents[x].combine_first(free_agents[y])
        free_agents.drop(columns=[x, y], inplace=True)
free_agents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       289 non-null    Int64
 1   player_name     289 non-null    object
 2   team_id_2425    289 non-null    int64
 3   tri_code_2425   289 non-null    object
 4   team_name_2425  289 non-null    object
 5   team_id_2526    0 non-null      Int64
 6   team_name_2526  0 non-null      object
 7   tri_code_2526   32 non-null     object
dtypes: Int64(2), int64(1), object(5)
memory usage: 18.8+ KB

In [764]:
free_agents[free_agents['player_name'].str.contains('marner', case=False, na=False)]

Empty DataFrame
Columns: [player_id, player_name, team_id_2425, tri_code_2425, team_name_2425, team_id_2526, team_name_2526, tri_code_2526]
Index: []

In [765]:
free_agents["player_id"] = free_agents["player_id"].astype('Int64').astype(int)
free_agents.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,team_name_2526,tri_code_2526
0,8479339,Patrik Laine,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
1,8479543,Michael Pezzetta,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
2,8475233,David Savard,8,MTL,Montréal Canadiens,<NA>,NaN,NaN
3,8478043,Sam Lafferty,7,BUF,Buffalo Sabres,<NA>,NaN,NaN
4,8480196,Jacob Bryson,7,BUF,Buffalo Sabres,<NA>,NaN,WPG

In [766]:
free_agents["action"] = np.where(free_agents['tri_code_2526'].notna(), "traded", "free agent")
free_agents.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,team_name_2526,tri_code_2526,action
0,8479339,Patrik Laine,8,MTL,Montréal Canadiens,<NA>,NaN,NaN,free agent
1,8479543,Michael Pezzetta,8,MTL,Montréal Canadiens,<NA>,NaN,NaN,free agent
2,8475233,David Savard,8,MTL,Montréal Canadiens,<NA>,NaN,NaN,free agent
3,8478043,Sam Lafferty,7,BUF,Buffalo Sabres,<NA>,NaN,NaN,free agent
4,8480196,Jacob Bryson,7,BUF,Buffalo Sabres,<NA>,NaN,WPG,traded

In [767]:

free_agents['tri_code_2526'] = np.where(free_agents['tri_code_2526']=='T.B', 'TBL', free_agents['tri_code_2526'])
free_agents['tri_code_2526'] = np.where(free_agents['tri_code_2526']=='N.J', 'NJD', free_agents['tri_code_2526']) 
free_agents['tri_code_2526'] = np.where(free_agents['tri_code_2526']=='L.A', 'LAK', free_agents['tri_code_2526'])
free_agents['tri_code_2526'] = np.where(free_agents['tri_code_2526']=='S.J', 'SJS', free_agents['tri_code_2526'])

In [768]:
for index, row in free_agents.iterrows():
    if row['action'] == "free agent":
        free_agents.at[index, 'team_id_2526'] = row['team_id_2425']
        free_agents.at[index, 'team_name_2526'] = row['team_name_2425']
        free_agents.at[index, 'tri_code_2526'] = row['tri_code_2425']
        
free_agents.head(10)

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,team_name_2526,tri_code_2526,action
0,8479339,Patrik Laine,8,MTL,Montréal Canadiens,8,Montréal Canadiens,MTL,free agent
1,8479543,Michael Pezzetta,8,MTL,Montréal Canadiens,8,Montréal Canadiens,MTL,free agent
2,8475233,David Savard,8,MTL,Montréal Canadiens,8,Montréal Canadiens,MTL,free agent
3,8478043,Sam Lafferty,7,BUF,Buffalo Sabres,7,Buffalo Sabres,BUF,free agent
4,8480196,Jacob Bryson,7,BUF,Buffalo Sabres,<NA>,NaN,WPG,traded
5,8473503,James Reimer,7,BUF,Buffalo Sabres,7,Buffalo Sabres,BUF,free agent
6,8482133,Thomas Bordeleau,28,SJS,San Jose Sharks,28,San Jose Sharks,SJS,free agent
7,8474053,Logan Couture,28,SJS,San Jose Sharks,28,San Jose Sharks,SJS,free agent
8,8479393,Noah Gregor,28,SJS,San Jose Sharks,28,San Jose Sharks,SJS,free agent
9,8479336,Carl Grundstrom,28,SJS,San Jose Sharks,28,San Jose Sharks,SJS,free agent

In [769]:

free_agents = free_agents.merge(
        teams,
       on='tri_code_2526',
        how="left",
        validate="m:1",
        indicator=True,
    )

x_cols = [c for c in free_agents.columns if c.endswith("_x")]

for x in x_cols:
    base = x[:-2]              # remove "_x"
    y = f"{base}_y"

    if y in free_agents.columns:
        free_agents[base] = free_agents[x].combine_first(free_agents[y])
        free_agents.drop(columns=[x, y], inplace=True)
free_agents.head()

,player_id,player_name,team_id_2425,tri_code_2425,team_name_2425,tri_code_2526,action,_merge,team_id_2526,team_name_2526
0,8479339,Patrik Laine,8,MTL,Montréal Canadiens,MTL,free agent,both,8,Montréal Canadiens
1,8479543,Michael Pezzetta,8,MTL,Montréal Canadiens,MTL,free agent,both,8,Montréal Canadiens
2,8475233,David Savard,8,MTL,Montréal Canadiens,MTL,free agent,both,8,Montréal Canadiens
3,8478043,Sam Lafferty,7,BUF,Buffalo Sabres,BUF,free agent,both,7,Buffalo Sabres
4,8480196,Jacob Bryson,7,BUF,Buffalo Sabres,WPG,traded,both,52,Winnipeg Jets

In [770]:
free_agents = free_agents.drop(columns = '_merge')

In [771]:
export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\free_agents.csv"
free_agents.to_csv(export_path, index=False)

In [772]:
off_season_trade.head()

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action
0,A.J. Greer,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade
2,Adam Edstrom,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade
18,Alex Tuch,8477949,7,BUF,Buffalo Sabres,15,WSH,Washington Capitals,off-season trade
27,Alexandre Texier,8480074,19,STL,St. Louis Blues,8,MTL,Montréal Canadiens,off-season trade
31,Andre Burakovsky,8477444,16,CHI,Chicago Blackhawks,9,OTT,Ottawa Senators,off-season trade

In [773]:
player_movement = pd.concat([off_season_trade, free_agents]).sort_values(by='player_name').reset_index(drop=True)
player_movement.head()

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action
0,A.J. Greer,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade
1,Adam Boqvist,8480871,2,NYI,New York Islanders,2,NYI,New York Islanders,free agent
2,Adam Edstrom,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade
3,Adam Henrique,8474641,22,EDM,Edmonton Oilers,22,EDM,Edmonton Oilers,free agent
4,Akil Thomas,8480851,26,LAK,Los Angeles Kings,26,LAK,Los Angeles Kings,free agent

In [774]:

player_movement["player_url"] = (
    "https://api-web.nhle.com/v1/player/" + player_movement["player_id"].astype(str) + "/landing"
)

player_movement.head()

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action,player_url
0,A.J. Greer,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade,https://api-web.nhle.com/v1/player/8478421/lan...
1,Adam Boqvist,8480871,2,NYI,New York Islanders,2,NYI,New York Islanders,free agent,https://api-web.nhle.com/v1/player/8480871/lan...
2,Adam Edstrom,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade,https://api-web.nhle.com/v1/player/8481726/lan...
3,Adam Henrique,8474641,22,EDM,Edmonton Oilers,22,EDM,Edmonton Oilers,free agent,https://api-web.nhle.com/v1/player/8474641/lan...
4,Akil Thomas,8480851,26,LAK,Los Angeles Kings,26,LAK,Los Angeles Kings,free agent,https://api-web.nhle.com/v1/player/8480851/lan...

In [ ]:
player_movement = player_movement.drop_duplicates()
# player_movement = player_movement.drop(index=220)
# player_movement = player_movement.drop(index=237)

In [783]:
player_movement[player_movement['player_id']==8481711]

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action,player_url
221,Matias Maccelli,8481711,10,TOR,Toronto Maple Leafs,10,TOR,Toronto Maple Leafs,free agent,https://api-web.nhle.com/v1/player/8481711/lan...

In [784]:
dupes = player_movement[player_movement.duplicated(subset = 'player_id')]
dupes

Empty DataFrame
Columns: [player_name, player_id, team_id_2425, tri_code_2425, team_name_2425, team_id_2526, tri_code_2526, team_name_2526, action, player_url]
Index: []

In [818]:
off_season = pd.DataFrame()
player_url = player_movement["player_url"].tolist()


def process_player_batch(player_batch):
    batch_players = []
    session = requests.Session()

    for item in player_batch:
        player_url = item["player_url"]

        while True:
            response = session.get(player_url)

            if response.status_code == 200:
                break

            if response.status_code == 429:
                wait = int(response.headers.get("Retry-After", 5))
                print(f"Rate limited. Waiting {wait} seconds...")
                time.sleep(wait)
                continue

            print(f"Request failed with status code {response.status_code}")
            response = None
            break

        if response is None:
            continue

        json_data = json.loads(response.text)

        player = pd.json_normalize(json_data).reindex(
            columns=[
                "playerId",
                "isActive",
                "currentTeamId",
                "currentTeamAbbrev",
            ]
        )

        player[["currentTeamId", "currentTeamAbbrev"]] = player[
            ["currentTeamId", "currentTeamAbbrev"]
        ].where(
            player[["currentTeamId", "currentTeamAbbrev"]].notna(),
            None
        )

        batch_players.append(player)

        time.sleep(0.2)

    if batch_players:
        return pd.concat(batch_players, ignore_index=True)

    return pd.DataFrame(
        columns=[
            "playerId",
            "isActive",
            "currentTeamId",
            "currentTeamAbbrev",
        ]
    )


player_batch = [{"player_url": url} for url in player_url]

batch_size = 100

for i in range(0, len(player_batch), batch_size):
    batch = player_batch[i:i + batch_size]
    batch_players = process_player_batch(batch)

    if not batch_players.empty:
        off_season = pd.concat(
            [off_season, batch_players],
            ignore_index=True
        )

off_season.reset_index(drop=True, inplace=True)



export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\off_season2.csv"
off_season.to_csv(export_path, index=False)

In [819]:
off_season = pd.read_csv( r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\off_season2.csv")

off_season=off_season[off_season['isActive']==True]

off_season = off_season.rename(columns = {'playerId':'player_id','currentTeamId':'new_team_id', 'currentTeamAbbrev':'new_team_tri_code'})
off_season['new_team_id'] = off_season['new_team_id'].astype('Int64')
off_season.head()

   player_id  isActive  new_team_id new_team_tri_code
0    8478421      True           24               ANA
2    8481726      True           18               NSH
4    8480851      True           23               VAN
5    8481033      True           13               FLA
8    8471214      True           15               WSH

In [813]:
# player_movement = player_movement.iloc[:, :9]

In [820]:
player_movement=player_movement.merge(off_season[['player_id','new_team_id', 'new_team_tri_code' ]], on='player_id', how='left')
x_cols = [c for c in player_movement.columns if c.endswith("_x")]

for x in x_cols:
    base = x[:-2]              # remove "_x"
    y = f"{base}_y"

    if y in player_movement.columns:
        player_movement[base] = player_movement[x].combine_first(player_movement[y])
        player_movement.drop(columns=[x, y], inplace=True)
player_movement.head()

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action,player_url,new_team_id,new_team_tri_code
0,A.J. Greer,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade,https://api-web.nhle.com/v1/player/8478421/lan...,24,ANA
1,Adam Boqvist,8480871,2,NYI,New York Islanders,2,NYI,New York Islanders,free agent - unsigned,https://api-web.nhle.com/v1/player/8480871/lan...,<NA>,NaN
2,Adam Edstrom,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade,https://api-web.nhle.com/v1/player/8481726/lan...,18,NSH
3,Adam Henrique,8474641,22,EDM,Edmonton Oilers,22,EDM,Edmonton Oilers,free agent - unsigned,https://api-web.nhle.com/v1/player/8474641/lan...,<NA>,NaN
4,Akil Thomas,8480851,26,LAK,Los Angeles Kings,26,LAK,Los Angeles Kings,free agent - signed,https://api-web.nhle.com/v1/player/8480851/lan...,23,VAN

In [821]:
for index, row in player_movement.iterrows():
    if row["action"] == "free agent":
        if pd.isna(row["new_team_id"]):
            player_movement.at[index, "action"] = "free agent - unsigned"
        else:
            player_movement.at[index, "action"] = "free agent - signed"
export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\player_movement.csv"
player_movement.to_csv(export_path, index=False)
player_movement.head()

,player_name,player_id,team_id_2425,tri_code_2425,team_name_2425,team_id_2526,tri_code_2526,team_name_2526,action,player_url,new_team_id,new_team_tri_code
0,A.J. Greer,8478421,13,FLA,Florida Panthers,24,ANA,Anaheim Ducks,off-season trade,https://api-web.nhle.com/v1/player/8478421/lan...,24,ANA
1,Adam Boqvist,8480871,2,NYI,New York Islanders,2,NYI,New York Islanders,free agent - unsigned,https://api-web.nhle.com/v1/player/8480871/lan...,<NA>,NaN
2,Adam Edstrom,8481726,3,NYR,New York Rangers,18,NSH,Nashville Predators,off-season trade,https://api-web.nhle.com/v1/player/8481726/lan...,18,NSH
3,Adam Henrique,8474641,22,EDM,Edmonton Oilers,22,EDM,Edmonton Oilers,free agent - unsigned,https://api-web.nhle.com/v1/player/8474641/lan...,<NA>,NaN
4,Akil Thomas,8480851,26,LAK,Los Angeles Kings,26,LAK,Los Angeles Kings,free agent - signed,https://api-web.nhle.com/v1/player/8480851/lan...,23,VAN

In [822]:
teams_update = teams.rename(columns ={'team_id_2526':'team_id','team_name_2526':'team_name'})

In [ ]:
data_upload = player_movement[['player_name', 'team_name_2425','team_name_2526','action', 'new_team_id', 'new_team_tri_code']]

data_upload = data_upload.merge(
        teams_update[['team_id','team_name']],
       left_on="new_team_id",
       right_on="team_id",
        how="left"
    ).drop(columns=["team_id",'new_team_id', 'new_team_tri_code'], errors="ignore")

x_cols = [c for c in data_upload.columns if c.endswith("_x")]

for x in x_cols:
    base = x[:-2]              # remove "_x"
    y = f"{base}_y"

    if y in data_upload.columns:
        data_upload[base] = data_upload[x].combine_first(data_upload[y])
        data_upload.drop(columns=[x, y], inplace=True)
        
data_upload = data_upload.rename(columns = {'player_name': 'Player Name', 
                                            'team_name_2425':'24-25 Team on 6/30/25', 
                                            'team_name_2526':'25-26 Team 0n 6/30/26', 
                                            'action':'Action', 
                                            'team_name':'26-27 Team'})
data_upload["Last Run"] = pd.Timestamp.now()
data_upload.head()

,Player Name,24-25 Team,25-26 Team,Action,26-27 Team,Last Run
0,A.J. Greer,Florida Panthers,Anaheim Ducks,off-season trade,Anaheim Ducks,2026-07-02 16:56:47.132255
1,Adam Boqvist,New York Islanders,New York Islanders,free agent - unsigned,NaN,2026-07-02 16:56:47.132255
2,Adam Edstrom,New York Rangers,Nashville Predators,off-season trade,Nashville Predators,2026-07-02 16:56:47.132255
3,Adam Henrique,Edmonton Oilers,Edmonton Oilers,free agent - unsigned,NaN,2026-07-02 16:56:47.132255
4,Akil Thomas,Los Angeles Kings,Los Angeles Kings,free agent - signed,Vancouver Canucks,2026-07-02 16:56:47.132255

In [828]:
moved_players = player_movement['player_id'].unique().tolist()


all_players = players.copy()
not_moved_players = all_players[~all_players['player_id'].isin(moved_players)]

not_moved_players.info()

<class 'pandas.core.frame.DataFrame'>
Index: 489 entries, 0 to 850
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       489 non-null    Int64
 1   player_name     489 non-null    object
 2   team_id_2425    489 non-null    int64
 3   tri_code_2425   489 non-null    object
 4   team_name_2425  489 non-null    object
 5   team_id_2526    489 non-null    Int64
 6   tri_code_2526   489 non-null    object
 7   team_name_2526  489 non-null    object
dtypes: Int64(2), int64(1), object(5)
memory usage: 35.3+ KB

In [829]:
export_path = r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\API data\not_moved_players.csv"
not_moved_players.to_csv(export_path, index=False)

In [824]:
import gspread
from gspread_dataframe import set_with_dataframe

gc = gspread.service_account(filename=r"C:\Users\kjchr\Desktop\hockey\new_hockey_env\Scripts\Scripts in Process\nhlapidata-24c664bdadf7.json")

spreadsheet = gc.open_by_key("16Ul_3lXJQ3u1HI0Ef1RTrd9_6dl5UbvwmETxWyeOxMM")
worksheet = spreadsheet.worksheet("Sheet1")


worksheet.clear()
set_with_dataframe(worksheet, data_upload)